---
- name: create a pod
  hosts: nodes
  tasks:
  - name: create deployment using ansible modules
    kubernetes.core.k8s:
      state: present
      definition:
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          creationTimestamp: null
          labels:
            app: dev-nginx-deployment
          name: dev-nginx-deployment
          namespace: dev-ns
        spec:
          replicas: 2
          selector:
            matchLabels:
              app: dev-nginx-deployment
          strategy: {}
          template:
            metadata:
              creationTimestamp: null
              labels:
                app: dev-nginx-deployment
            spec:
              containers:
                - image: nginx:latest
                  name: nginx
                  resources: {}
          status: {}
